import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, Clock3, FlaskConical, LockKeyhole, Mail, MapPin, Menu, Microscope, Phone, Search, ShieldCheck, Upload, X } from 'lucide-react';
import './styles.css';
import './map.css';
import './knowledge.css';
import './logo.css';

const fallback = {
  about: 'Laboratori Alfa ofron diagnostikim laboratorik të besueshëm, të mbështetur në përvojë profesionale dhe kujdes për pacientin.',
  mission: 'Diagnostikim laboratorik i saktë, i besueshëm dhe i mbështetur në prova shkencore.',
  contactAddress: 'Tiranë, Shqipëri', contactHours: 'Për orarin e shërbimit, ju lutemi na kontaktoni.', contactPhone: 'Shtoni numrin e telefonit nga paneli i administratorit.', contactEmail: 'Shtoni email-in nga paneli i administratorit.'
};
const alfaMap = { coordinates: '41.3390853,19.8277466', directions: 'https://www.google.com/maps/dir/?api=1&destination=41.3390853%2C19.8277466&travelmode=driving' };
const api = async (url, options = {}) => { const response = await fetch(url, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || 'Diçka shkoi keq.'); return response.status === 204 ? null : response.json(); };
const pageUrl = slug => `/sherbimet/${encodeURIComponent(slug)}`;

// The catalog is populated after the root page loads. When browser history
// returns to /#sherbimet, wait for that async content, then restore its section.
if (typeof window !== 'undefined' && window.location.hash) {
  const restoreHashTarget = () => {
    const target = document.getElementById(window.location.hash.slice(1));
    if (!target) return false;
    window.scrollTo({ top: target.getBoundingClientRect().top + window.scrollY - 94, behavior: 'auto' });
    return true;
  };
  const watchForHashTarget = () => {
    if (restoreHashTarget()) return;
    const observer = new MutationObserver(() => {
      if (restoreHashTarget()) observer.disconnect();
    });
    observer.observe(document.body, { childList: true, subtree: true });
    window.setTimeout(() => observer.disconnect(), 10000);
  };
  document.readyState === 'loading'
    ? window.addEventListener('DOMContentLoaded', watchForHashTarget, { once: true })
    : watchForHashTarget();
}

function Logo() { return <a className="logo" href="/"><span>α</span><b>Laboratori<br/>Alfa</b></a>; }

function Header({ menu, setMenu }) {
  return <header><Logo/><button className="menu-button" aria-label="Hap menunë" onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button><nav className={menu ? 'open' : ''}><a href="/#rreth">Rreth nesh</a><a href="/#pse-alfa">Pse Alfa?</a><a href="/#sherbimet">Shërbimet</a><a href="/#artikuj">Artikuj</a><a href="/#kontakt">Kontakt</a></nav><a className="header-cta" href="/#sherbimet">Katalogu i analizave <ArrowRight size={16}/></a></header>;
}

function PageGrid({ pages }) {
  const [query, setQuery] = useState('');
  const visible = useMemo(() => pages.filter(page => `${page.title} ${page.category} ${page.section}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [pages, query]);
  const groups = useMemo(() => [...new Set(visible.map(page => page.section))], [visible]);
  return <section className="service-section" id="sherbimet"><div className="section-heading"><div><p className="eyebrow">Katalogu i shërbimeve</p><h2>Gjeni analizën ose infeksionin që po <em>kërkoni.</em></h2></div><p>Çdo temë hap një faqe të veçantë me përgatitjen e mostrës dhe informacionin laboratorik të përgatitur nga Laboratori Alfa.</p></div><label className="search"><Search size={18}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Kërko Onikomikoza, HBV, TSH…"/></label><div className="knowledge-grid">{groups.map(section => <article className="knowledge-group" key={section}><div className="knowledge-group-title"><BookOpen size={17}/><div><span>{visible.find(x => x.section === section)?.category}</span><h3>{section}</h3></div></div><div>{visible.filter(x => x.section === section).map(page => <a className="knowledge-link" href={pageUrl(page.slug)} key={page.slug}><span>{page.title}</span><ChevronRight size={16}/></a>)}</div></article>)}</div>{!visible.length && <p className="empty-state">Nuk u gjet asnjë rezultat për këtë kërkim.</p>}</section>;
}

function Articles({ articles }) { return <section className="articles" id="artikuj"><div className="section-heading"><div><p className="eyebrow">Artikuj & udhëzime</p><h2>Njohuri që e bëjnë kujdesin <em>më të qartë.</em></h2></div><p>Materiale të përzgjedhura për pacientët dhe profesionistët e shëndetit.</p></div><div className="article-grid">{articles.slice(0,6).map((article, i) => <article className="article-card" key={article.id}><div className={`article-image image-${i % 3}`}>{article.imageId ? <img src={`/api/images/${article.imageId}`} alt=""/> : <FlaskConical/>}<span>{article.category}</span></div><div><h3>{article.title}</h3><p>{article.excerpt}</p>{article.body && <p className="article-body-preview">{article.body.slice(0, 150)}…</p>}</div></article>)}</div></section>; }

function Contact({ content, sent, onSubmit }) { return <section className="contact" id="kontakt"><div className="contact-copy"><p className="eyebrow">Kontakt</p><h2>Jemi këtu për t’ju <em>ndihmuar.</em></h2><p>Për pyetje mbi shërbimet laboratorike ose për informacion rreth përgatitjes për analiza, shkruani ose kontaktoni laboratorin.</p><div className="contact-list"><p><MapPin/> <span><strong>Adresa</strong>{content.contactAddress}</span></p><p><Clock3/> <span><strong>Orari</strong>{content.contactHours}</span></p><p><Phone/> <span><strong>Telefoni</strong>{content.contactPhone}</span></p><p><Mail/> <span><strong>Email</strong>{content.contactEmail}</span></p></div><div className="map-card"><div className="map-card-head"><MapPin size={18}/><span><strong>Gjeni Laboratorin Alfa</strong><small>Hapni hartën ose nisni drejtimin menjëherë.</small></span></div><iframe title="Harta e Laboratorit Alfa" loading="lazy" src={`https://www.google.com/maps?q=${alfaMap.coordinates}&z=16&output=embed`}/><a className="button map-directions" href={alfaMap.directions} target="_blank" rel="noreferrer">Merr drejtimin në Google Maps <ArrowRight size={16}/></a></div></div><form className="contact-form" onSubmit={onSubmit}><label>Emri<input required name="name" placeholder="Emri juaj"/></label><label>Email<input required type="email" name="email" placeholder="email@shembull.al"/></label><label>Mesazhi<textarea required name="message" placeholder="Si mund t’ju ndihmojmë?"/></label><button className="button primary">Dërgo mesazhin <ArrowRight size={16}/></button>{sent && <small>Faleminderit. Mesazhi u ruajt me sukses.</small>}</form></section>; }

function Admin({ onClose, content, setContent, articles, setArticles }) {
  const [authenticated, setAuthenticated] = useState(false); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const [draft, setDraft] = useState({ title: '', excerpt: '', body: '', category: 'Artikuj', imageId: null }); const [editing, setEditing] = useState(null);
  useEffect(() => { api('/api/admin/session').then(() => setAuthenticated(true)).catch(() => {}); }, []);
  const login = async e => { e.preventDefault(); try { await api('/api/admin/login', { method: 'POST', body: JSON.stringify({ password }) }); setAuthenticated(true); } catch (err) { setError(err.message); } };
  const saveContent = key => api(`/api/admin/content/${key}`, { method: 'PUT', body: JSON.stringify({ value: content[key] }) });
  const upload = async file => { const form = new FormData(); form.append('image', file); const response = await fetch('/api/admin/images', { method: 'POST', body: form }); if (!response.ok) throw new Error('Ngarkimi dështoi.'); const image = await response.json(); setDraft(item => ({ ...item, imageId: image.id })); };
  const saveArticle = async e => { e.preventDefault(); const item = editing ? await api(`/api/admin/articles/${editing}`, { method: 'PUT', body: JSON.stringify(draft) }) : await api('/api/admin/articles', { method: 'POST', body: JSON.stringify(draft) }); setArticles(old => editing ? old.map(article => article.id === item.id ? item : article) : [item, ...old]); setEditing(null); setDraft({ title: '', excerpt: '', body: '', category: 'Artikuj', imageId: null }); };
  if (!authenticated) return <div className="admin-overlay"><div className="admin-login"><button className="close" onClick={onClose}><X/></button><LockKeyhole/><p className="eyebrow">Hapësirë private</p><h2>Administratori</h2><form onSubmit={login}><input type="password" autoFocus placeholder="Fjalëkalimi" value={password} onChange={e => setPassword(e.target.value)}/>{error && <small>{error}</small>}<button className="button primary">Hyr në panel <ArrowRight size={16}/></button></form></div></div>;
  return <div className="admin-overlay"><aside className="admin-panel"><div className="admin-top"><div><p className="eyebrow">Panel privat</p><h2>Redakto përmbajtjen</h2></div><button className="close" onClick={onClose}><X/></button></div><section><h3>Kontakt</h3>{[['contactAddress','Adresa'],['contactHours','Orari'],['contactPhone','Telefoni'],['contactEmail','Email']].map(([key, label]) => <label className="edit-field" key={key}><span>{label}</span><textarea value={content[key] || ''} onChange={e => setContent(old => ({ ...old, [key]: e.target.value }))} onBlur={() => saveContent(key)}/></label>)}</section><section><div className="admin-title"><h3>{editing ? 'Redakto artikullin' : 'Artikull i ri'}</h3>{editing && <button onClick={() => { setEditing(null); setDraft({ title: '', excerpt: '', body: '', category: 'Artikuj', imageId: null }); }}>Anulo</button>}</div><form className="article-form" onSubmit={saveArticle}><input required placeholder="Titulli" value={draft.title} onChange={e => setDraft(item => ({ ...item, title: e.target.value }))}/><input required placeholder="Kategoria" value={draft.category} onChange={e => setDraft(item => ({ ...item, category: e.target.value }))}/><textarea required placeholder="Përmbledhja" value={draft.excerpt} onChange={e => setDraft(item => ({ ...item, excerpt: e.target.value }))}/><textarea placeholder="Teksti i plotë" value={draft.body || ''} onChange={e => setDraft(item => ({ ...item, body: e.target.value }))}/><label className="upload"><Upload size={16}/>{draft.imageId ? 'Foto e bashkëngjitur' : 'Shto foto (maks. 5 MB)'}<input type="file" accept="image/*" onChange={e => e.target.files[0] && upload(e.target.files[0])}/></label><button className="button primary">Ruaj artikullin <Check size={16}/></button></form></section><section><h3>Artikujt ekzistues</h3>{articles.map(article => <div className="admin-article" key={article.id}><span>{article.title}</span><button onClick={() => { setEditing(article.id); setDraft(article); }}>Redakto</button><button className="danger" onClick={async () => { await api(`/api/admin/articles/${article.id}`, { method: 'DELETE' }); setArticles(old => old.filter(item => item.id !== article.id)); }}>Fshi</button></div>)}</section></aside></div>;
}

function Home({ content, pages, articles, setArticles, admin, setAdmin, sent, onContact }) { const [menu, setMenu] = useState(false); return <><Header menu={menu} setMenu={setMenu}/><main><section className="hero" id="fillimi"><div className="hero-copy"><p className="eyebrow">Diagnostikim laboratorik · Tiranë</p><h1>Qartësi për çdo<br/><em>hap të shëndetit.</em></h1><p className="hero-text">Rezultate laboratorike të besueshme, të mbështetura në përvojë, profesionalizëm dhe kujdes për pacientin.</p><div className="hero-actions"><a className="button primary" href="#sherbimet">Eksploro shërbimet <ArrowRight size={17}/></a><a className="button ghost" href="#kontakt">Na kontaktoni</a></div><div className="hero-trust"><ShieldCheck/><span><strong>Që prej vitit 2008</strong><br/>me fokus te cilësia e rezultatit</span></div></div><div className="hero-visual"><div className="orb orb-one"></div><div className="orb orb-two"></div><div className="tube"><i></i><b></b></div><div className="visual-note"><Microscope size={20}/><span>Ekspertizë në<br/><strong>Mikrobiologji</strong></span></div></div></section><section className="intro" id="rreth"><div><p className="eyebrow">Laboratori Alfa</p><h2>Një përgjigje e saktë fillon me një proces të bërë <em>me kujdes.</em></h2></div><div><p>{content.about}</p><a href="/#sherbimet" className="text-link">Shihni katalogun e plotë <ArrowRight size={16}/></a></div></section><section className="reasons" id="pse-alfa"><div className="section-heading"><div><p className="eyebrow">Pse të zgjidhni Alfa?</p><h2>Besimi ndërtohet <em>në çdo detaj.</em></h2></div></div><div className="reason-grid">{[[ShieldCheck,'Përvojë profesionale','Mbi 29 vite përvojë në laboratorin klinik dhe mikrobiologjik.'],[FlaskConical,'Metoda bashkëkohore','Analiza të realizuara me fokus te saktësia dhe cilësia.'],[LockKeyhole,'Etikë & konfidencialitet','Respekt maksimal për privatësinë dhe të dhënat e pacientit.'],[Microscope,'Ekspertizë në mikrobiologji','Një nga pikat më të forta të Laboratorit Alfa.']].map(([Icon,title,text]) => <article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section><PageGrid pages={pages}/><Articles articles={articles}/><Contact content={content} sent={sent} onSubmit={onContact}/></main><footer><Logo/><p>© {new Date().getFullYear()} Laboratori Alfa. Diagnostikim me besim.</p><button onClick={() => setAdmin(true)}>Admin</button></footer>{admin && <Admin onClose={() => setAdmin(false)} content={content} setContent={() => {}} articles={articles} setArticles={setArticles}/>}</>; }

function KnowledgePage({ slug }) { const [page, setPage] = useState(null); const [related, setRelated] = useState([]); const [menu, setMenu] = useState(false); useEffect(() => { api(`/api/knowledge/${encodeURIComponent(slug)}`).then(item => { setPage(item); api('/api/knowledge').then(items => setRelated(items.filter(x => x.section === item.section && x.slug !== item.slug).slice(0, 7))); }).catch(() => setPage(false)); }, [slug]); if (page === null) return <><Header menu={menu} setMenu={setMenu}/><main className="loading-page">Duke hapur temën…</main></>; if (!page) return <><Header menu={menu} setMenu={setMenu}/><main className="loading-page"><h1>Faqja nuk u gjet.</h1><a className="button primary" href="/#sherbimet">Kthehu te katalogu</a></main></>; return <><Header menu={menu} setMenu={setMenu}/><main className="knowledge-page"><a className="back-link" href="/#sherbimet"><ArrowLeft size={17}/> Katalogu i shërbimeve</a><p className="eyebrow">{page.category} · {page.section}</p><h1>{page.title}</h1><div className="knowledge-layout"><article className="knowledge-article">{page.body.split(/\n\n+/).filter(Boolean).map((paragraph, index) => <p className={/^[🧪📋⚠️]/u.test(paragraph) ? 'knowledge-heading' : ''} key={index}>{paragraph}</p>)}<div className="medical-note"><ShieldCheck size={19}/><span>Informacioni është orientues dhe nuk zëvendëson këshillën e mjekut. Për interpretimin e rezultateve, konsultohuni me profesionistin shëndetësor.</span></div></article><aside className="related-pages"><p className="eyebrow">Në të njëjtin sektor</p>{related.map(item => <a href={pageUrl(item.slug)} key={item.slug}>{item.title}<ChevronRight size={15}/></a>)}</aside></div></main><footer><Logo/><p>© {new Date().getFullYear()} Laboratori Alfa.</p></footer></>; }

function App() { const [content, setContent] = useState(fallback); const [pages, setPages] = useState([]); const [articles, setArticles] = useState([]); const [admin, setAdmin] = useState(false); const [sent, setSent] = useState(false); useEffect(() => { api('/api/content').then(data => setContent(old => ({ ...old, ...data }))).catch(() => {}); api('/api/knowledge').then(setPages).catch(() => {}); api('/api/articles').then(setArticles).catch(() => {}); }, []); const contact = async e => { e.preventDefault(); try { await api('/api/contact', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(e.target))) }); setSent(true); e.target.reset(); } catch {} }; const slug = window.location.pathname.startsWith('/sherbimet/') ? decodeURIComponent(window.location.pathname.slice('/sherbimet/'.length)) : ''; return slug ? <KnowledgePage slug={slug}/> : <Home content={content} pages={pages} articles={articles} setArticles={setArticles} admin={admin} setAdmin={setAdmin} sent={sent} onContact={contact}/>; }

createRoot(document.getElementById('root')).render(<App/>);
